title: "Fintry Energy Decision Framework"
description: "Short project subtitle"
theme: just-the-docs

# Enable top navigation
just_the_docs:
  top_navigation: true
  homepage: index

# Navigation links
nav:
  - title: Home
    url: /
  - title: Methodology
    url: /methodology/
  - title: Case Study
    url: /case-study/
  - title: Modeling
    url: /modeling/
  - title: Conclusions
    url: /conclusions/
  - title: Team
    url: /team/
