theme: jekyll-theme-minimal
title: Fintry Energy Decision Framework
description: Short project subtitle

top_navigation:
  - title: Home
    url: /
  - title: Methodology
    url: /methodology/
  - title: Case Study
    url: /case-study/
  - title: Modeling
    url: /modeling/
  - title: Conclusions
    url: /conclusions/
  - title: Team
    url: /team/
